vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.NvimTreeToggle)
vim.api.nvim_set_keymap('n', '<LEADER>1', '<cmd>lua require("bufferline").go_to_buffer(1, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>2', '<cmd>lua require("bufferline").go_to_buffer(2, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>3', '<cmd>lua require("bufferline").go_to_buffer(3, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>4', '<cmd>lua require("bufferline").go_to_buffer(4, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>5', '<cmd>lua require("bufferline").go_to_buffer(5, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>6', '<cmd>lua require("bufferline").go_to_buffer(6, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>7', '<cmd>lua require("bufferline").go_to_buffer(7, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>8', '<cmd>lua require("bufferline").go_to_buffer(8, true)<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<LEADER>9', '<cmd>lua require("bufferline").go_to_buffer(9, true)<cr>', { noremap = true, silent = true })
vim.keymap.set("n", "<leader>l",'<CMD>BufferLineCycleNext<CR>')
vim.keymap.set("n", "<leader>h", '<CMD>BufferLineCyclePrev<CR>')
