vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.NvimTreeToggle)
vim.keymap.set('n', '<leader>1', ':LualineBuffersJump! 1<CR>', { silent = true })
vim.keymap.set('n', '<leader>2', ':LualineBuffersJump! 2<CR>', { silent = true })
vim.keymap.set('n', '<leader>3', ':LualineBuffersJump! 3<CR>', { silent = true })
vim.keymap.set('n', '<leader>4', ':LualineBuffersJump! 4<CR>', { silent = true })
vim.keymap.set('n', '<leader>5', ':LualineBuffersJump! 5<CR>', { silent = true })
vim.keymap.set('n', '<leader>6', ':LualineBuffersJump! 6<CR>', { silent = true })
vim.keymap.set('n', '<leader>7', ':LualineBuffersJump! 7<CR>', { silent = true })
vim.keymap.set('n', '<leader>8', ':LualineBuffersJump! 8<CR>', { silent = true })
vim.keymap.set('n', '<leader>9', ':LualineBuffersJump! 9<CR>', { silent = true })
vim.keymap.set("n", "<Leader>h", ":bprevious<CR>", { silent = true })
vim.keymap.set("n", "<Leader>l", ":bnext<CR>", { silent = true })
vim.keymap.set("n", "<Leader>q", ":bdelete<CR>", { silent = true })
